--Crear BASE DE DATOS LLAMADA dbCursosOnline

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TblUsuario')
DROP TABLE TblUsuario
GO
create table TblUsuario(
	id int identity not null primary key,
	nombres varchar(200) null,
	primerApellido varchar(100) null,
	segundoApellido varchar(100) null,
	fechaNacimiento DateTime null,
	lugarNacimiento varchar(100) null,
	direccion varchar(200) null,
	genero varchar(20) null,
	pasaTiempos varchar(500)	
)

--select * from TblUsuario
GO
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TblPasatiempos')
DROP TABLE TblPasatiempos
GO
create table TblPasatiempos(
	id int identity not null primary key,
	nombre varchar(200) null,
)
GO
BEGIN
insert into  TblPasatiempos values ('ABEJAS (CRIANZA ABEJAS APICULTURA)')
insert into  TblPasatiempos values ('ACTUAR EN TEATRO')
insert into  TblPasatiempos values ('ACUARIOS')
insert into  TblPasatiempos values ('AEROBIC')
insert into  TblPasatiempos values ('AEROMODELISMO')
insert into  TblPasatiempos values ('AEROSTACION')
insert into  TblPasatiempos values ('AIKIDO')
insert into  TblPasatiempos values ('AIRSOFT')
insert into  TblPasatiempos values ('AJEDREZ')
insert into  TblPasatiempos values ('ANIMACION ( CREACION CINE ANIMACION DIBUJOS ANIMADOS)')
insert into  TblPasatiempos values ('AQUAGYM')
insert into  TblPasatiempos values ('AROMATERAPIA')
insert into  TblPasatiempos values ('ARTE DIGITAL')
insert into  TblPasatiempos values ('ARTE:ASISTIR A ESPECTACULOS CULTURALES (TEATRO,MUSICA,DANZA,OPERA,ZARZUELA)')
insert into  TblPasatiempos values ('ASTROLOGIA')
insert into  TblPasatiempos values ('ASTRONOMIA')
insert into  TblPasatiempos values ('ATLETISMO')
insert into  TblPasatiempos values ('AUDIOLIBROS')
insert into  TblPasatiempos values ('AUTOCARAVANAS')
insert into  TblPasatiempos values ('AUTOMOVILES CLASICOS/ANTIGUOS')
insert into  TblPasatiempos values ('AVIACION DEPORTIVA (RECREATIVA)')
insert into  TblPasatiempos values ('AVICULTURA (CRIA GALLINAS)')
insert into  TblPasatiempos values ('AVISTAMIENTO AVES')
insert into  TblPasatiempos values ('BACKGAMMON')
insert into  TblPasatiempos values ('BADMINTON')
insert into  TblPasatiempos values ('BAILAR')
insert into  TblPasatiempos values ('BAILE BARRA (POLE DANCE, POLE FITNESS)')
insert into  TblPasatiempos values ('BALONCESTO')
insert into  TblPasatiempos values ('BALONMANO')
insert into  TblPasatiempos values ('BANDA O GRUPO MUSICALES')
insert into  TblPasatiempos values ('BARCOS MOTOR')
insert into  TblPasatiempos values ('BARRANQUISMO')
insert into  TblPasatiempos values ('BATIK Y ESTAMPACION TEJIDOS')
insert into  TblPasatiempos values ('BEISBOL')
insert into  TblPasatiempos values ('BELLEZA Y ESTETICA (AFICION A)')
insert into  TblPasatiempos values ('BIATLON')
insert into  TblPasatiempos values ('BIBLIOFILIA')
insert into  TblPasatiempos values ('BICICLETA (CICLISMO)')
insert into  TblPasatiempos values ('BICICLETA MONTAÑA')
insert into  TblPasatiempos values ('BIKEJORING')
insert into  TblPasatiempos values ('BILLAR')
insert into  TblPasatiempos values ('BINGO')
insert into  TblPasatiempos values ('BLOG (Y VIDEOBLOG)')
insert into  TblPasatiempos values ('BMX (BICICLETA MOTOCROSS)')
insert into  TblPasatiempos values ('BODYBOARD')
insert into  TblPasatiempos values ('BOLOS (BOWLING, BOLICHE)')
insert into  TblPasatiempos values ('BONSAI (ARBOLES ENANOS)')
insert into  TblPasatiempos values ('BORDADO SOBRE PAPEL')
insert into  TblPasatiempos values ('BOXEO')
insert into  TblPasatiempos values ('BRICOLAJE O DIY')
insert into  TblPasatiempos values ('BUCEO (SUBMARINISMO)')
insert into  TblPasatiempos values ('CABALLO (MONTAR, HIPICA, EQUITACION)')
insert into  TblPasatiempos values ('CALIGRAFIA Y LETTERING')
insert into  TblPasatiempos values ('CAMPISMO')
insert into  TblPasatiempos values ('CANARICULTURA')
insert into  TblPasatiempos values ('CANICROSS')
insert into  TblPasatiempos values ('CANTAR')
insert into  TblPasatiempos values ('CAPOEIRA (TIPO LUCHA BRASILEÑA)')
insert into  TblPasatiempos values ('CARPINTERIA')
insert into  TblPasatiempos values ('CARRERAS POR MONTAÑA')
insert into  TblPasatiempos values ('CARROVELA Y BLOKART (LAND SAILING)')
insert into  TblPasatiempos values ('CASAS DE MUÑECAS (CONSTRUCCION DE)')
insert into  TblPasatiempos values ('CATA DE CERVEZA')
insert into  TblPasatiempos values ('CATA DE VINO')
insert into  TblPasatiempos values ('CAZA (DEPORTIVA)')
insert into  TblPasatiempos values ('CERAMICA')
insert into  TblPasatiempos values ('CERVEZA (FABRICACION CASERA DE)')
insert into  TblPasatiempos values ('CESTERIA')
insert into  TblPasatiempos values ('CETRERIA (AMAESTRAMIENTO DE AVES RAPACES)')
insert into  TblPasatiempos values ('CHALKPAINT (PINTURA DE TIZA)')
insert into  TblPasatiempos values ('CHI KUNG O QUI GONG')
insert into  TblPasatiempos values ('CIANOTIPIA')
insert into  TblPasatiempos values ('CICLOTURISMO')
insert into  TblPasatiempos values ('CINE')
insert into  TblPasatiempos values ('COCINA')
insert into  TblPasatiempos values ('COLECCIONAR (SELLOS,MONEDAS,ANTIGÜEDADES)')
insert into  TblPasatiempos values ('COLOREAR LIBROS')
insert into  TblPasatiempos values ('COMETAS (VOLAR COMETAS)')
insert into  TblPasatiempos values ('COMICS (CREACION DE )')
insert into  TblPasatiempos values ('COMICS (LECTURA DE)')
insert into  TblPasatiempos values ('COMIDISTA (FOODIE)')
insert into  TblPasatiempos values ('COMPOSICION MUSICAL')
insert into  TblPasatiempos values ('COMPOSTAJE')
insert into  TblPasatiempos values ('COMPRAR (O VENDER: ROPA, COMPLEMENTOS, OBJETOS, ETC)')
insert into  TblPasatiempos values ('CONDUCCIÓN DE AUTOMÓVILES (AUTOMOVILISMO DEPORTIVO)')
insert into  TblPasatiempos values ('CONDUCCION DE MOTOCICLETAS (MOTOCICLISMO)')
insert into  TblPasatiempos values ('CONFERENCIAS(ASISTIR A)')
insert into  TblPasatiempos values ('CORO')
insert into  TblPasatiempos values ('CORRER (RUNNING)')
insert into  TblPasatiempos values ('COSMETICA')
insert into  TblPasatiempos values ('COSTURA, CORTE Y CONFECCION')
insert into  TblPasatiempos values ('CRISTAL TEÑIDO')
insert into  TblPasatiempos values ('CROQUET')
insert into  TblPasatiempos values ('CRUCEROS (VIAJES DE)')
insert into  TblPasatiempos values ('CUBO DE RUBIK (ROMPECABEZAS)')
insert into  TblPasatiempos values ('CUERO (CREACIONES CON)')
insert into  TblPasatiempos values ('CULTURISMO (BODY BUILDING)')
insert into  TblPasatiempos values ('CURLING')
insert into  TblPasatiempos values ('CUSTOMIZACION ROPA')
insert into  TblPasatiempos values ('CUSTOMIZACION Y RESTAURACION BICICLETAS')
insert into  TblPasatiempos values ('DAMAS (JUEGO DE)')
insert into  TblPasatiempos values ('DANZA AEREA')
insert into  TblPasatiempos values ('DARDOS (LANZAR DARDOS)')
insert into  TblPasatiempos values ('DECORACION DE INTERIORES')
insert into  TblPasatiempos values ('DECOUPAGE (DECORACION DE SUPERFICIES)')
insert into  TblPasatiempos values ('DEPORTE (ASISTIR ESPECTACULOS DEPORTIVOS)')
insert into  TblPasatiempos values ('DEPORTE (VER DEPORTE EN TV, ONLINE, REVISTAS PERIODICOS, RADIO)')
insert into  TblPasatiempos values ('DEPORTES DE FANTASIA (LIGA DE FANTASIA)')
insert into  TblPasatiempos values ('DIARIO (ESCRIBIR UN)')
insert into  TblPasatiempos values ('DIBUJO ARTISTICO')
insert into  TblPasatiempos values ('DIORAMAS (Y BELENES)')
insert into  TblPasatiempos values ('DIRIGIR, ENTRENAR, GESTIONAR.')
insert into  TblPasatiempos values ('DISC GOLF')
insert into  TblPasatiempos values ('DISEÑO DE ROPA (MODA)')
insert into  TblPasatiempos values ('DISEÑO Y CREACION DE PAGINAS WEB')
insert into  TblPasatiempos values ('DJ (DISK JOCKEY)')
insert into  TblPasatiempos values ('DOCUMENTALES (AFICION A LOS)')
insert into  TblPasatiempos values ('DOMINO')
insert into  TblPasatiempos values ('ELECTRONICA')
insert into  TblPasatiempos values ('ENCUADERNACION DE LIBROS')
insert into  TblPasatiempos values ('ENMARCAR CUADROS')
insert into  TblPasatiempos values ('ESCALADA')
insert into  TblPasatiempos values ('ESCRIBIR LITERATURA (PROSA,POESIA,TEATRO, ENSAYO,GUIONES)')
insert into  TblPasatiempos values ('ESCULTURA')
insert into  TblPasatiempos values ('ESGRIMA')
insert into  TblPasatiempos values ('ESMALTES SOBRE METAL (AL FUEGO)')
insert into  TblPasatiempos values ('ESPELEOLOGIA')
insert into  TblPasatiempos values ('ESPORTS')
insert into  TblPasatiempos values ('ESQUI ALPINO')
insert into  TblPasatiempos values ('ESQUI DE FONDO O NORDICO')
insert into  TblPasatiempos values ('ESQUI NAUTICO O ACUATICO')
insert into  TblPasatiempos values ('ESTUDIAR (IDIOMAS, OTRAS ASIGNATURAS,ETC)')
insert into  TblPasatiempos values ('EXPLORACION URBANA (URBEX)')
insert into  TblPasatiempos values ('FLAMENCO')
insert into  TblPasatiempos values ('FLOORBALL (O UNIHOCKEY)')
insert into  TblPasatiempos values ('FLORES KANZASHI')
insert into  TblPasatiempos values ('FLORES SECAS (TRABAJAR CON)')
insert into  TblPasatiempos values ('FLYBOARD')
insert into  TblPasatiempos values ('FOTOGRAFIA')
insert into  TblPasatiempos values ('FRISBEE (DISCO VOLADOR)')
insert into  TblPasatiempos values ('FRONTON')
insert into  TblPasatiempos values ('FUTBOL')
insert into  TblPasatiempos values ('FUTBOL AMERICANO')
insert into  TblPasatiempos values ('FUTBOL SALA')
insert into  TblPasatiempos values ('FUTBOLIN')
insert into  TblPasatiempos values ('GENEALOGIA E HISTORIA FAMILIAR')
insert into  TblPasatiempos values ('GEOCACHING Y BUSQUEDA DE TESOROS')
insert into  TblPasatiempos values ('GIMNASIA DE MANTENIMIENTO Y FITNESS')
insert into  TblPasatiempos values ('GLOBOS (TRABAJO CON GLOBOS MOLDEABLES)')
insert into  TblPasatiempos values ('GO (JUEGO)')
insert into  TblPasatiempos values ('GOLF')
insert into  TblPasatiempos values ('GRABADOS ARTISTICOS')
insert into  TblPasatiempos values ('GRAFFITI ARTE URBANO')
insert into  TblPasatiempos values ('HACER VINO')
insert into  TblPasatiempos values ('HALTEROFILIA (LEVANTAMIENTO PESAS)')
insert into  TblPasatiempos values ('HAPKIDO')
insert into  TblPasatiempos values ('HISTORIA (AFICION A LA)')
insert into  TblPasatiempos values ('HOCKEY DE MESA (AIR HOCKEY)')
insert into  TblPasatiempos values ('HOCKEY SOBRE HIELO')
insert into  TblPasatiempos values ('HOCKEY SOBRE HIERBA')
insert into  TblPasatiempos values ('HOCKEY SOBRE PATINES')
insert into  TblPasatiempos values ('HOCKEY SUBACUATICO')
insert into  TblPasatiempos values ('HORTICULTURA (AGRICULTURA)')
insert into  TblPasatiempos values ('HUERTO CASERO')
insert into  TblPasatiempos values ('HYDROSPEED')
insert into  TblPasatiempos values ('IKEBANA ( Y ARTE FLORAL)')
insert into  TblPasatiempos values ('INTERNET (NAVEGAR POR)')
insert into  TblPasatiempos values ('INVERTIR EN BOLSA')
insert into  TblPasatiempos values ('JABON (HACER)')
insert into  TblPasatiempos values ('JARDINERIA')
insert into  TblPasatiempos values ('JIU JITSU')
insert into  TblPasatiempos values ('JOYAS Y BISUTERIA (CREACION DE)')
insert into  TblPasatiempos values ('JUDO')
insert into  TblPasatiempos values ('VIDEOJUEGOS')
insert into  TblPasatiempos values ('JUEGOS CON FICHAS (GENERAL)')
insert into  TblPasatiempos values ('JUEGOS DE CARTAS O NAIPES')
insert into  TblPasatiempos values ('JUEGOS DE MESA (GENERAL)')
insert into  TblPasatiempos values ('JUEGOS DE MESA TEMATICOS')
insert into  TblPasatiempos values ('JUEGOS DE ROL')
insert into  TblPasatiempos values ('JUGGER')
insert into  TblPasatiempos values ('KARAOKE')
insert into  TblPasatiempos values ('KARATE')
insert into  TblPasatiempos values ('KAYAK POLO')
insert into  TblPasatiempos values ('KENDO')
insert into  TblPasatiempos values ('KENPO')
insert into  TblPasatiempos values ('KICK BOXING')
insert into  TblPasatiempos values ('KINTSUGI')
insert into  TblPasatiempos values ('KITESURF')
insert into  TblPasatiempos values ('KOKEDAMAS (PLANTAS SOBRE MUSGO)')
insert into  TblPasatiempos values ('KORFBALL')
insert into  TblPasatiempos values ('KUNG FU')
insert into  TblPasatiempos values ('LABORES (PUNTO, BORDADO, ENCAJE,ETC)')
insert into  TblPasatiempos values ('LECTURA')
insert into  TblPasatiempos values ('LEGO (CONSTRUCCIONES CON PIEZAS)')
insert into  TblPasatiempos values ('LOCK PICKING (ABRIR CERRADURAS)')
insert into  TblPasatiempos values ('LOMOGRAFIA')
insert into  TblPasatiempos values ('LOTERIA')
insert into  TblPasatiempos values ('LUCHA (OLIMPICA, GRECORROMANA…..)')
insert into  TblPasatiempos values ('MADERA (TALLAS EN MADERA)')
insert into  TblPasatiempos values ('MAGIA (ILUSIONISMO, PRESTIDIGITACION)')
insert into  TblPasatiempos values ('MAHJONG (JUEGO DE FICHAS CHINO)')
insert into  TblPasatiempos values ('MALABARES')
insert into  TblPasatiempos values ('MARCHA O PASEO NORDICO (NORDIC WALKING)')
insert into  TblPasatiempos values ('MARIONETAS (TEATRO DE)')
insert into  TblPasatiempos values ('MEDITACION')
insert into  TblPasatiempos values ('MERCADILLOS/FLEA MARKETS')
insert into  TblPasatiempos values ('MERMELADAS (PREPARAR)')
insert into  TblPasatiempos values ('METALES (BUSQUEDA DE)')
insert into  TblPasatiempos values ('MINDFULNESS O ATENCIÓN PLENA')
insert into  TblPasatiempos values ('MINERALES (BUSQUEDA DE)')
insert into  TblPasatiempos values ('MODA (AFICION A LA MODA)')
insert into  TblPasatiempos values ('MODELISMO (AVIONES,COCHES,BARCOS,DRONES, FIGURAS,ETC)')
insert into  TblPasatiempos values ('MODELISMO CON CERILLAS')
insert into  TblPasatiempos values ('MONTAÑISMO/ALPINISMO')
insert into  TblPasatiempos values ('MOTO ACUATICA')
insert into  TblPasatiempos values ('MUÑECAS (HACER)')
insert into  TblPasatiempos values ('MUSHING')
insert into  TblPasatiempos values ('MUSICA (AFICION A LA)')
insert into  TblPasatiempos values ('NADAR (NATACION)')
insert into  TblPasatiempos values ('OBSERVACION DE TRENES Y AVIONES')
insert into  TblPasatiempos values ('ORIENTACION')
insert into  TblPasatiempos values ('ORIGAMI (O PAPIROFLEXIA)')
insert into  TblPasatiempos values ('PADBOL')
insert into  TblPasatiempos values ('PADDLE SURF (SURF A REMO)')
insert into  TblPasatiempos values ('PADEL')
insert into  TblPasatiempos values ('PAINTBALL')
insert into  TblPasatiempos values ('PALOMAS (CRIA DE PALOMAS, COLOMBOFILIA Y COLOMBICULTURA)')
insert into  TblPasatiempos values ('PAPEL MACHE')
insert into  TblPasatiempos values ('PARACAIDISMO')
insert into  TblPasatiempos values ('PARAMOTOR')
insert into  TblPasatiempos values ('PARAPENTE')
insert into  TblPasatiempos values ('PARKOUR (FREERUNNING)')
insert into  TblPasatiempos values ('PASATIEMPOS (CRUCIGRAMAS, SUDOKUS, INFANTILES, MEMORIA, ETC…)')
insert into  TblPasatiempos values ('PASEAR')
insert into  TblPasatiempos values ('PATCHWORK Y COLCHAS')
insert into  TblPasatiempos values ('PATINAJE SOBRE HIELO')
insert into  TblPasatiempos values ('PATINAJE SOBRE RUEDAS (ROLLER)')
insert into  TblPasatiempos values ('PERROS (CONCURSOS/EXHIBICIONES)')
insert into  TblPasatiempos values ('PESCA')
insert into  TblPasatiempos values ('PESCA SUBMARINA')
insert into  TblPasatiempos values ('PETANCA')
insert into  TblPasatiempos values ('PILATES')
insert into  TblPasatiempos values ('PING PONG O TENIS DE MESA')
insert into  TblPasatiempos values ('PINTURA ARTISTICA')
insert into  TblPasatiempos values ('PINTURA DE FIGURAS (POLICROMADO,DORADO)')
insert into  TblPasatiempos values ('PINTURA SOBRE SEDA')
insert into  TblPasatiempos values ('PIRAGÜISMO (CANOISMO/CANOTAJE)')
insert into  TblPasatiempos values ('PLANTAS DE INTERIOR')
insert into  TblPasatiempos values ('PLANTAS SILVESTRES, INCLUIDOS ARBOLES Y ARBUSTOS (AFICION A LAS)')
insert into  TblPasatiempos values ('PODCASTS (AFICION/CREACION)')
insert into  TblPasatiempos values ('POLO')
insert into  TblPasatiempos values ('PORCELANA FRIA')
insert into  TblPasatiempos values ('POWERLIFTING')
insert into  TblPasatiempos values ('PRODUCCION MUSICAL')
insert into  TblPasatiempos values ('PROGRAMACION INFORMATICA')
insert into  TblPasatiempos values ('PUZZLES')
insert into  TblPasatiempos values ('QUAD Y BUGGY')
insert into  TblPasatiempos values ('RADIO (AFICION A LA)')
insert into  TblPasatiempos values ('RADIOAFICION')
insert into  TblPasatiempos values ('RAFTING')
insert into  TblPasatiempos values ('RAQUETAS DE NIEVE')
insert into  TblPasatiempos values ('RECICLAJE CREATIVO')
insert into  TblPasatiempos values ('REDES SOCIALES (FACEBOOK, YOUTUBE,TWITTER,INSTAGRAM,ETC)')
insert into  TblPasatiempos values ('REIKI (TECNICA ESPIRITUAL SANADORA)')
insert into  TblPasatiempos values ('REMO DEPORTIVO')
insert into  TblPasatiempos values ('REPOSTERIA/PASTELERIA Y CUPCAKES')
insert into  TblPasatiempos values ('REPUJADO DE METAL')
insert into  TblPasatiempos values ('RESTAURACION DE COCHES CLASICOS')
insert into  TblPasatiempos values ('RESTAURACION DE MUEBLES')
insert into  TblPasatiempos values ('REVISTAS Y PERIODICOS (LEER)')
insert into  TblPasatiempos values ('ROBOTICA')
insert into  TblPasatiempos values ('ROLLER DERBY')
insert into  TblPasatiempos values ('RUGBY')
insert into  TblPasatiempos values ('SCALEXTRIC')
insert into  TblPasatiempos values ('SCRAPBOOK (ALBUM DE RECORTES)')
insert into  TblPasatiempos values ('SENDERISMO')
insert into  TblPasatiempos values ('SERIES DE TV (AFICION A LAS SERIES)')
insert into  TblPasatiempos values ('SERIGRAFIA')
insert into  TblPasatiempos values ('SETAS (BUSQUEDA O RECOLECCIÓN DE)')
insert into  TblPasatiempos values ('SKATEBOARDING')
insert into  TblPasatiempos values ('SLIME (JUGAR CON SLIME, UNA MASA VISCOSA )')
insert into  TblPasatiempos values ('SNOWBIKE')
insert into  TblPasatiempos values ('SNOWBOARD')
insert into  TblPasatiempos values ('SOFTBALL')
insert into  TblPasatiempos values ('SPEEDRIDING')
insert into  TblPasatiempos values ('SPINNING')
insert into  TblPasatiempos values ('SQUASH')
insert into  TblPasatiempos values ('SURF')
insert into  TblPasatiempos values ('TAEKWONDO')
insert into  TblPasatiempos values ('TAICHI')
insert into  TblPasatiempos values ('TAMPONES O SELLOS DE CAUCHO (CREACION CON)')
insert into  TblPasatiempos values ('TAROT')
insert into  TblPasatiempos values ('TATUAJES')
insert into  TblPasatiempos values ('TAXIDERMIA')
insert into  TblPasatiempos values ('TEJER (CON UN TELAR CASERO)')
insert into  TblPasatiempos values ('TEJO (JUEGO COLOMBIANO)')
insert into  TblPasatiempos values ('TENIS')
insert into  TblPasatiempos values ('TINTADO/TEÑIDO DE TEJIDOS')
insert into  TblPasatiempos values ('TIRO CON ARCO')
insert into  TblPasatiempos values ('TIRO CON TIRACHINAS')
insert into  TblPasatiempos values ('TIRO DE HACHA')
insert into  TblPasatiempos values ('TIRO DEPORTIVO CON ARMA DE FUEGO')
insert into  TblPasatiempos values ('TOCAR UN INSTRUMENTO MUSICAL')
insert into  TblPasatiempos values ('TOROS')
insert into  TblPasatiempos values ('TOSTAR CAFE')
insert into  TblPasatiempos values ('TRANSFERENCIA DE IMAGENES')
insert into  TblPasatiempos values ('TRENES A ESCALA')
insert into  TblPasatiempos values ('TRIATLON')
insert into  TblPasatiempos values ('UÑAS (DECORACION DE)')
insert into  TblPasatiempos values ('VEHICULOS DE CONTROL REMOTO (RC)')
insert into  TblPasatiempos values ('VELA DEPORTIVA Y RECREATIVA')
insert into  TblPasatiempos values ('VELAS (CREACION DE VELAS)')
insert into  TblPasatiempos values ('VIAJAR')
insert into  TblPasatiempos values ('VIAJAR LENTAMENTE (SLOW TRAVEL)')
insert into  TblPasatiempos values ('VIAJES DE AVENTURA')
insert into  TblPasatiempos values ('VIAJES TEMATICOS')
insert into  TblPasatiempos values ('VIDEO (REALIZACION DE VIDEOS)')
insert into  TblPasatiempos values ('VIDEOJUEGOS')
insert into  TblPasatiempos values ('VISITAR MONUMENTOS Y YACIMIENTOS ARQUEOLÓGICOS')
insert into  TblPasatiempos values ('VISITAR MUSEOS Y EXPOSICIONES')
insert into  TblPasatiempos values ('VISITAS URBANAS')
insert into  TblPasatiempos values ('VOLEIBOL')
insert into  TblPasatiempos values ('VOLUNTARIADO AMBIENTAL')
insert into  TblPasatiempos values ('VOLUNTARIADO ANIMAL')
insert into  TblPasatiempos values ('VOLUNTARIADO CULTURAL')
insert into  TblPasatiempos values ('VOLUNTARIADO EN DEPORTE')
insert into  TblPasatiempos values ('VOLUNTARIADO SOCIAL')
insert into  TblPasatiempos values ('VUELO A VELA (VUELO SIN MOTOR)')
insert into  TblPasatiempos values ('WAKEBOARD')
insert into  TblPasatiempos values ('WATERPOLO')
insert into  TblPasatiempos values ('WINDSURF')
insert into  TblPasatiempos values ('YOGA')
insert into  TblPasatiempos values ('YOUTUBER')
insert into  TblPasatiempos values ('ZUMBA')
END

--select * from TblPasatiempos
GO
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TblPasatiemposUsuario')
DROP TABLE TblPasatiemposUsuario
GO
create table TblPasatiemposUsuario(
	idPasatiempo int,
	idUsuario int
)

--select * from TblPasatiemposUsuario
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_TraerPasatiemposUsuario')
DROP PROCEDURE SP_TraerPasatiemposUsuario
GO
CREATE PROC SP_TraerPasatiemposUsuario AS 
BEGIN
	select USU.nombres + ' ' + USU.primerApellido + ' ' + USU.segundoApellido AS NOMBRE,
		PT.nombre AS PASATIEMPO from TblPasatiempos PT
	INNER JOIN TblPasatiemposUsuario PTUSU ON PTUSU.idPasatiempo = PT.id
	INNER JOIN TblUsuario USU ON USU.id = PTUSU.idUsuario
END
--exec SP_TraerPasatiemposUsuario

GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_VerificarEdades')
DROP PROCEDURE SP_VerificarEdades
GO
CREATE PROC SP_VerificarEdades AS
BEGIN
 Select ISNULL(SUM(A.PRIM), 0) as [Menos_10], ISNULL(SUM(A.SEG), 0) AS [11-20], ISNULL(SUM(A.TERC), 0) AS [21-50], ISNULL(SUM(A.CUAR), 0) AS [MAS_50] from
	(SELECT SUM(CASE WHEN Edad < 10 THEN 1 ELSE 0 END) AS PRIM,
        SUM(CASE WHEN Edad BETWEEN 11 AND 20 THEN 1 ELSE 0 END) AS SEG,
        SUM(CASE WHEN Edad BETWEEN 21 AND 50 THEN 1 ELSE 0 END) AS TERC,
		SUM(CASE WHEN Edad > 50 THEN 1 ELSE 0 END) AS CUAR
	from 
	(select (cast(datediff(dd,fechaNacimiento,GETDATE()) / 365.25 as int)) AS EDAD from TblUsuario) T
	group by EDAD) A
END

--exec SP_VerificarEdades
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_VerificarGenero')
DROP PROCEDURE SP_VerificarGenero
GO
CREATE PROC SP_VerificarGenero AS
BEGIN
	if ((select COUNT(*) from TblUsuario) > 0)
	BEGIN
	select COUNT(*) CANTIDAD,
	(CASE WHEN genero = 0 THEN 'MASCULINO' 
		ELSE (CASE WHEN genero = 1 THEN 'FEMENINO' ELSE 'OTRO' END)END) AS [GENERO]
	from TblUsuario group by genero
	END
	ELSE
	BEGIN
		select 0, ''
	END
END

--exec SP_VerificarGenero